console.log("Te amo gabi")
console.log("Just you!")
console.log("Gracias por estar conmigo gabi")
console.log("por favor perdobame gabi")
console.log('Empiezo a entender')
console.log("Malu Cumpleaños")