console.log("Te amo gabi")
console.log("Just you!")
console.log("Gracias por estar conmigo gabi")
console.log("por favor perdobame gabi")
console.log('Empiezo a entender')
console.log("Malu Cumpleaños")
console.log('this is all')
console.log('Colombia v Ghana')
console.log('Holla')
console.log('Mexico vs Inglaterra')
console.log("Testy")
