console.log('Una nueva semana')
console.log('uni')
console.log('Calculo')
console.log('Fisica')
console.log('Fisica')
console.log('Gabi')
console.log('I need to improve')
console.log('Quiz de fisica')
