console.log("Te amo gabi")
console.log("Just you!")
console.log("Gracias por estar conmigo gabi")
console.log("por favor perdobame gabi")
console.log('Empiezo a entender')
console.log("Malu Cumpleaños")
console.log('this is all')
console.log('Colombia v Ghana')
console.log('Holla')
console.log('Mexico vs Inglaterra')
console.log("Testy")
console.log("Hoy pasaron muchas cosas, felicidades ma por tu trabajo")
console.log("Francias vs Marruecos")
console.log("QUJIERO QUE ME AMES POR SIEMPRE")
console.log("just one more log")
console.log("DRAMA")
console.log("Te amo peque gabi")
console.log("Holis Gabi")
console.log("Pruebas medicas")
console.log("Test")
console.log("Sutherland")
console.log("medico")
console.log("Well Done!")
console.log("España 1 - Argentina 0")
console.log("Hoy me enoje con gabi")
console.log("Primer dia en Sutherland")
console.log("Segundo dia es sutherland")
