console.log("Te amo gabi")
console.log("Just you!")
console.log("Gracias por estar conmigo gabi")
console.log("por favor perdobame gabi")
console.log('Empiezo a entender')
console.log("Malu Cumpleaños")
console.log('this is all')
console.log('Colombia v Ghana')
console.log('Holla')
console.log('Mexico vs Inglaterra')
console.log("Testy")
console.log("Hoy pasaron muchas cosas, felicidades ma por tu trabajo")
console.log("Francias vs Marruecos")
console.log("QUJIERO QUE ME AMES POR SIEMPRE")
console.log("just one more log")
console.log("DRAMA")
console.log("Te amo peque gabi")
console.log("Holis Gabi")
console.log("Pruebas medicas")
console.log("Test")
console.log("Sutherland")
console.log("medico")
console.log("Well Done!")
console.log("España 1 - Argentina 0")
console.log("Hoy me enoje con gabi")
console.log("Primer dia en Sutherland")
console.log("Jorge")
console.log("Segundo dia es sutherland")
console.log("Pagos abuelita")
console.log("Texto")
console.log("Me gusta que duermas mi amor ")
console.log("I miss u")
console.log('new day')
console.log('Igleia')
console.log('Estas bien abuelita')
console.log('jello')
console.log('just another log')
console.log('Resistence')
console.log('Discusion')
console.log("Spiderman")
console.log("Estoy cansado")
console.log("Just log it")
console.log("Vamos a ver mi github")
console.log('amor')
console.log("Dios mio")
console.log('ojala me reconozca')
console.log('Universidad')
console.log('Uni 2do semestre')
console.log('Days')
console.log('Para no perder la costumbre')
console.lod('yo estoy aca porque tiene un proposito')
console.log('hola ')
console.log("Vaya! Falle, adivinen por que ??")
console.log('A dormir!')
console.log('La extraño')
console.log('Go go dolls - iris')
console.log("que rabia tengo")
console.log('Mas de la uni')
console.log('futbol con felipe')
console.log("HOY, completamente me libre de holberton, gracias a Dios")
console.log('just another log')
